# Generated by Django 4.2.7 on 2023-11-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_paper_generator_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(to="question_paper_generator_app.question"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionPaperGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_marks", models.IntegerField()),
                ("distribution", models.JSONField()),
                (
                    "question_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_paper_generator_app.questionstore",
                    ),
                ),
            ],
        ),
    ]
